#!/bin/bash

# Remove output directory if it exists
hdfs dfs -rm -r -f spadoopframes_mr

# Run MRJob
python3 q1.py -r hadoop hdfs:///datasets/cities --output-dir hdfs:///user/$USER/spadoopframes_mr
